# .circleci/config.yml
version: 2.1
orbs:
    slack: circleci/slack@4.12.5
    macos: circleci/macos@2
jobs:
  build-and-test:
    macos:
      xcode: 14.1.0
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    executor: ios_builder
    steps:
      - checkout
      - run: bundle install
      - run: bundle update fastlane
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan
      - slack/notify:
          channel: C05JPH36YQH
          event: pass
          template: basic_success_1

  adhoc:
    macos:
      xcode: 14.1.0
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: adhoc
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output

workflows:
  build-test-adhoc:
    jobs:
      - build-and-test
      - adhoc:
          filters:
            branches:
              only: development
          requires:
            - build-and-test

