# fastlane/Fastfile
default_platform :ios

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "すべてのテストを実行"
  lane :test do
    ENV["FASTLANE_XCODE_LIST_TIMEOUT"] = "120" 
    ENV['FL_UNLOCK_KEYCHAIN_PATH'] = 'login.keychain'
    ENV['FL_UNLOCK_KEYCHAIN_PASSWORD'] = 'password' 
    scan(
	include_simulator_logs: false
	)
  end

  desc "アドホック ビルド"
  lane :adhoc do
    match(type: "adhoc")
    gym(export_method: "ad-hoc")
  end
end